#!/bin/bash

set -o pipefail         # proper status code for a pipeline
set -o errexit          # exit when seeing a nonzero status code (set -e)
set -o nounset          # using unbound variable is an error (set -u)
shopt -s failglob       # pathname expansion failing is an error

EXE=${BASH_SOURCE[0]}
CTR=0
while [[ -L $EXE ]]; do
  (( ++CTR <= 100 )) || { echo Too many level of symlinks; exit 1; }
  DIR=$( cd -P "$( dirname "$EXE" )" && pwd )
  EXE=$( readlink "$EXE" )
  [[ $EXE = /* ]] || EXE=$DIR/$EXE
done
__DIR__=$( cd -P "$( dirname "$EXE" )" && pwd )
__NAME__=$( basename "$EXE" )
__FILE__=$__DIR__/$__NAME__
cd "$__DIR__/.."




exec mitm-server/programs/ssl/ssl_server2 \
        server_addr=0.0.0.0 \
        server_port=20443 \
        crt_file=mitm-server/localhost.crtchain \
        key_file=mitm-server/localhost.key
